# Generated by Django 5.1 on 2024-08-20 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_date_joined_remove_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'parol generatsiyasi',
                'verbose_name_plural': 'parol generatsiyalari',
            },
        ),
    ]
