# Generated by Django 5.1 on 2024-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_generatepassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatepassword',
            options={'ordering': ['-time'], 'verbose_name': 'parol generatsiyasi', 'verbose_name_plural': 'parol generatsiyalari'},
        ),
        migrations.AlterField(
            model_name='generatepassword',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
